config/routes.rb
HackaNewsApp::Application.routes.draw do
  root to: "links#index"

  post "/up", to: "link_votes#up"

  resources :links
  resources :users do
    resources :links, only: [:index]
  end

  resources :comments

  resource :session, only: [:new, :create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :commentor_id,
                  :link_id, :ancestor_ids, :descendant_ids

  belongs_to :commentor, class_name: "User", foreign_key: "commentor_id"
  belongs_to :link, inverse_of: :comment
  has_many :ancestor_relations, class_name: "Relation", foreign_key: "descendant_id"
  has_many :descendant_relations, class_name: "Relation", foreign_key: "ancestor_id"
  has_many :ancestors, through: :ancestor_relations
  has_many :descendants, through: :descendant_relations
  validates :content, :commentor_id, :link, presence: true

  def get_ancestors
    self.ancestors
  end

  def self.get_indent(descendant, ancestor)
    Comment.get_indent_helper(descendant, ancestor, 1)
  end

  def self.get_indent_helper(descendant, ancestor, counter)
    if descendant.parent_id == ancestor.id
      counter
    else
      Comment.get_indent_helper(Comment.find(descendant.parent_id), ancestor, counter + 1)
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :author_id, :title, :comments_attributes

  has_many :comments, inverse_of: :link
  has_many :link_votes
  belongs_to :author, class_name: "User"

  accepts_nested_attributes_for :comments, reject_if: :all_blank

  validates :title, :url, :author_id, presence: true

  def self.best_order
    Link.joins('LEFT OUTER JOIN link_votes ON links.id = link_votes.link_id')
        .group("link_id")
        .order("sum(link_votes.amount) DESC")
    ###this only shows links with votes in the last 24 hours, we want it
    # to show all links, but only count the votes in the last 24 hours!
  end

  def number_of_comments
    self.comments.count
  end

  def vote_sum
    self.link_votes.sum('amount')
  end
end

app/models/link_vote.rb
class LinkVote < ActiveRecord::Base
  attr_accessible :amount, :link_id, :user_id

  belongs_to :link
  belongs_to :user

  validates :link_id, :uniqueness => { scope: :user_id }
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  attr_accessible :ancestor_id, :descendant_id

  belongs_to :ancestor, class_name: "Comment"
  belongs_to :descendant, class_name: "Comment"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :remember_token

  has_many :links, foreign_key: :author_id
  has_many :comments,  foreign_key: :commentor_id
  has_many :link_votes

  validates :name, :password, presence: true

  def karma
    self.links.joins(:link_votes).sum('amount')
  end

  def average
    self.links.joins(:link_votes).sum(:amount)/self.links.count.to_f
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find(params[:id])
  end
end

app/controllers/link_votes_controller.rb
class LinkVotesController < ApplicationController
  before_filter :allowed_to_vote

  def up
    vote = LinkVote.new(user_id: current_user.id, link_id: params[:link_id], amount: 1)
    if vote.save
      flash[:success] = "You upvoted"
    else
      flash[:error] = "You have already voted on that link"
    end
    redirect_to root_path
  end

  private

    def allowed_to_vote
      unless current_user.karma > 1
        flash[:error] = "You need higher karma"
        redirect_to root_path
      end
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :logged_in_user, except: [:index]

  def index
    if params[:user_id]
      @links = User.find(params[:user_id]).links
    else
      @links = Link.best_order
    end
  end

  def new
    @link = Link.new
    @link.comments.build
  end

  def create
    @link = Link.new(params[:link])
    @link.author_id = current_user.id
    if @link.save
      flash[:success] = "You have added #{@link.title} to Hacka News"
      redirect_to root_url
    else
      render :new
    end
  end

  private

    def logged_in_user
      redirect_to new_session_url unless logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_name(params[:user][:name])
    if @user && @user.password == params[:user][:password]
      flash[:success] = "Logged In!"
      login @user
      redirect_to root_url
    else
      flash[:error] = "Incorrect Password"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login(@user)
      redirect_to root_url
    else
      flash[:error] = "Invalid Input"
      redirect_to new_session_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    user.remember_token = SecureRandom.hex(16)
    user.save
    session[:remember_token] = user.remember_token
  end

  def logout
    current_user.remember_token = nil
    current_user.save
    session[:remember_token] = nil
  end

  def current_user
    return nil if session[:remember_token].nil?
    @user ||= User.find_by_remember_token(session[:remember_token])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<div class="votes"> | User: <%= comment.commentor.name %></div>

app/views/comments/show.html.erb
<div class="comments">
<%= render partial: 'comment', object: @comment %>

<% @comment.descendants.each do |descendant| %>
  <div class="indent<%= Comment.get_indent(descendant, @comment)%>"><%= render partial: 'comment', object: descendant %></div>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackaNewsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Hacka News", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-left">
              <li><%= link_to "Submit", new_link_path %></li>
              <!-- more links -->

            </ul>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%#= link_to "Help",    '#' %></li>
              <% if logged_in? %>
                <li><%= link_to current_user.name, user_path(current_user) %></li>
                <li><%= link_to "Sign out", session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign in", new_session_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">

      <% flash.each do |key, msg| %>
        <div class="alert alert-<%= key %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/index.html.erb
<h1>Links</h1>

<ul>
  <% @links.each do |link| %>
    <li><%= link_to image_tag("uparrow.gif"), up_path(link_id: link.id), method: :post %>

      Link: <%= link_to link.title, link.url, :target => "_blank" %></li>
    <div class="votes"><%= link.vote_sum%> points by <%= link.author.name %>
                        <%= time_ago_in_words(link.created_at) %> |
                        <%= link.number_of_comments %> comments</div>
  <% end %>
</ul>

app/views/links/new.html.erb
<%= form_for(@link) do |f| %>
  <ul>
  <% @link.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br>
  <%= f.submit "Submit Link" %> <br><br><br>

  <%= f.fields_for(:comments) do |comments_form| %>
    <%= comments_form.label :content, "Comment" %>
    <%= comments_form.text_area :content %>

  <% end %>

<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %>'s page</h2>
<ul>
  <li>User: <%= @user.name %></li>
  <li>Created: <%= @user.created_at.strftime("%B %d, %Y") %></li>
  <li>Karma: <%= @user.karma %></li>
  <li>Average: <%= @user.average %></li>
</ul>

<%= link_to "Submissions", user_links_path(@user) %> <br/>
<%= link_to "Comments", "" %>